parameters:
  pool: 'ubuntu-latest'
  name: 'Terraform'
  terraformVersion: '<%= terraformVersion %>'
  workingDirectory: '$(System.DefaultWorkingDirectory)'


jobs:
- job: Validate${{ parameters.name}}
  displayName: 'Terraform - Validate'
  pool:
    vmImage: ${{ parameters.pool }}

  steps:
  - task: TerraformInstaller@0
    displayName: 'Terraform - Install'
    inputs:
        terraformVersion: '${{ parameters.terraformVersion }}'

  - task: TerraformCLI@0
    displayName: "Terraform - Init"
    inputs:
      command: 'init'
      workingDirectory: ${{ parameters.workingDirectory }}
      backendType: 'local'

  - task: TerraformCLI@0
    displayName: "Terraform - Validate"
    inputs:
        command: 'validate'
        workingDirectory: ${{ parameters.workingDirectory }}
        commandOptions: '${{ parameters.validateCommandOptions }}'