enabled: true
controller:
    ingressClass: ${INGRESS_CLASS}
    replicaCount: ${INGRESS_REPLICAS}
    service:
      loadBalancerIP: "${LOAD_BALANCER_IP}"
      externalTrafficPolicy: Local
      annotations: {    
        <% if (internalLoadBalancer == true) { %>
        service.beta.kubernetes.io/azure-load-balancer-internal: true,
        service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "${INGRESS_SERVICE_SUBNET}"
        <% } else { %>
        service.beta.kubernetes.io/azure-load-balancer: true
        <% } %>
      }