parameters:
  pool: 'ubuntu-latest'
  name: 'generator'
  nodeVersionSpec: '12.x'
  workingDirectory: '$(System.DefaultWorkingDirectory)'

jobs:
- job: Build${{ parameters.name}}
  displayName: 'Build - ${{ parameters.name}}'
  pool:
    vmImage: ${{ parameters.pool }}

  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '${{ parameters.nodeVersionSpec}}'
    displayName: 'Node.js - Install'

  - task: Npm@1
    displayName: 'NPM - Install'
    inputs:
      command: 'install'

  - task: AzureCLI@2
    displayName: 'NPM - Test'
    inputs:
      azureSubscription: '${{ parameters.azureSubscription }}'
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
          az --version
          az account show
          npm test
          
  - script: |
      npm publish --dry-run
    displayName: 'NPM - Publish (dry run)'