parameters:
  pool: 'ubuntu-latest'
  name: 'generator'
  nodeVersionSpec: '10.x'
  workingDirectory: '$(System.DefaultWorkingDirectory)'
  tagVersion: '$(Build_SourceBranch)'

jobs:
- job: Build${{ parameters.name}}
  displayName: 'Build - ${{ parameters.name}}'
  pool:
    vmImage: ${{ parameters.pool }}

  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '${{ parameters.nodeVersionSpec}}'
    displayName: 'Node.js - Install'

  - script: |
      npm install
    displayName: 'NPM - Install'

  - script: |
      npm publish --tag ${{ parameters.tagVersion}}
    displayName: 'NPM - Publish'    