parameters:
  pool: 'ubuntu-latest'
  name: 'generator'
  nodeVersionSpec: '10.x'
  workingDirectory: '$(System.DefaultWorkingDirectory)'

jobs:
- job: Publish${{ parameters.name}}
  displayName: 'Publish - ${{ parameters.name}}'
  pool:
    vmImage: ${{ parameters.pool }}

  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '${{ parameters.nodeVersionSpec}}'
    displayName: 'Node.js - Install'

  - task: Npm@1
    displayName: 'NPM - Install'  
    inputs:
      command: 'install'

  - script: |
      npm publish --access public
    displayName: 'NPM - Publish'